//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal_Master
    {
        public decimal paId { get; set; }
        public decimal empCode { get; set; }
        public decimal rm_empCode { get; set; }
        public string period { get; set; }
        public System.DateTime createdon { get; set; }
        public System.DateTime expiredon { get; set; }
        public string emp_status { get; set; }
        public Nullable<System.DateTime> emp_date { get; set; }
        public string rm_status { get; set; }
        public Nullable<System.DateTime> rm_date { get; set; }
    }
}
