//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Review_Master
    {
        public decimal id { get; set; }
        public decimal paid { get; set; }
        public Nullable<int> qualityofworkntaskcompletion { get; set; }
        public Nullable<int> goalsntargetachievement { get; set; }
        public Nullable<int> writtennverbalcommunicationskills { get; set; }
        public Nullable<int> initiativenmotivation { get; set; }
        public Nullable<int> teamworknleadershipskills { get; set; }
        public Nullable<int> abilitytoproblemsolve { get; set; }
        public Nullable<int> attendancenregualrization { get; set; }
        public Nullable<int> total { get; set; }
        public string comment { get; set; }
    }
}
