//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATSAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordExpiry_Master
    {
        public decimal Employeecode { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public System.DateTime ExpirtyDate { get; set; }
    }
}
